name: node
on: [push]
jobs:
    node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  check-latest: true
                  cache: 'npm'
            - name: Install node_modules
              run: npm ci
            - name: Run linter
              run: npm run lint
            - name: Run tests
              run: npm run test
            - name: Build project
              run: npm run build
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: build
                  retention-days: 3
